complete HW
Scofa26/AQA_MTS pull request #1
Opened 2023-11-18 19:34 UTC by Scofa26

2023-11-20 21:48 UTC, wildpioneer requested changes

2023-11-20 21:48 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +            double DoOperation(double x1, double y1, string oper1)
1. Мы еще методы не изучали - ну теперь я знаю, что ты знакома с методами
2. Метод вызываемый 1 раз не имеет никакого смысла

2023-11-20 21:48 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +
А почему тут 2-ве пусты строки, хотя до этого была только 1. Придерживайся единообразия по всей программе

2023-11-20 21:48 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +            Console.WriteLine($"{z} нечетное? : {check(z % 2)}");
С функциональной точки зрения это такой же метод как и 1-ый, но вот технически сделано верно - мне понравилось

2023-11-21 17:54 UTC, Scofa26 commented
done HW1

2023-11-21 17:55 UTC, merged