6 HW task ready
Scofa26/AQA_MTS pull request #2
Opened 2023-11-26 12:35 UTC by Scofa26

2023-11-27 19:31 UTC, wildpioneer requested changes

2023-11-27 19:31 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +                 if (array[i] == number) flag = true;
А если мы уже нашли вхождение элемента - то зачем нам дальше продолжать поиск?

2023-11-27 19:31 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +                     if (i == j) continue;
Вот тут совсем не понял - нужно пояснение с твоей стороны

2023-11-27 19:31 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +                      Console.WriteLine($" \n max = {max} \n min = {min} \n Sum/n = {sum / n}");
Средний элемент это не среднее арифметическое
1 5 10  
Средний 5
Среднее арифметическое 5.3

2023-11-27 19:31 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +
Форматирование - пустые строки - следи за ними внимательно

2023-11-27 19:31 UTC, wildpioneer commented on AQA_MTS/Program.cs
> +             if (Convert.ToDouble(sum3 / 2.0) == Convert.ToDouble(sum4 / 2.0)) Console.WriteLine("Средние арифметические равны ");
1. Так - тут опять не понял - почему ты сумму делишь на 2? Ведь среднее арифметическое это сумма / количество элементов
2. Нужно расчет среднего арифметического вынести в переменные и посчитать до проверки

2023-11-28 15:24 UTC, Scofa26 commented on AQA_MTS/Program.cs
> +                 if (array[i] == number) flag = true;
![image](https://github.com/Scofa26/AQA_MTS/assets/125700209/1c5f2a98-dea3-4088-80e5-70af29d63664)
Исправила - добавила break

2023-11-28 15:25 UTC, Scofa26 commented on AQA_MTS/Program.cs
> +                     if (i == j) continue;
В верхнем цикле я искала индекс подходящего по условие задачи числа, т.е. которое нужно удалить. И далее я решила создать копию исходного массива, но без указанного числа. И тут как раз я проверяю, если индекс текущего равен индексу числа, которого нужно удалить, я континью, тем самым пропуская это число к добавлению

2023-11-28 15:25 UTC, Scofa26 commented on AQA_MTS/Program.cs
> +                      Console.WriteLine($" \n max = {max} \n min = {min} \n Sum/n = {sum / n}");
В этой задаче я решила найти и среднее и ср. арифметическое 
как раз ниже в строках 137 - 140 я нахожу и вывожу среднее 
![image](https://github.com/Scofa26/AQA_MTS/assets/125700209/337d585a-9eff-4333-8d6d-55bd1e0f37fc)

2023-11-28 15:25 UTC, Scofa26 commented on AQA_MTS/Program.cs
> +
удалила пустую строку, но пришлось вручную, потому что стандартное форматирование VS этого не сделало (

2023-11-28 15:25 UTC, Scofa26 commented on AQA_MTS/Program.cs
> +             if (Convert.ToDouble(sum3 / 2.0) == Convert.ToDouble(sum4 / 2.0)) Console.WriteLine("Средние арифметические равны ");
Да, тут ошиблась и делила на 2. Исправила ) 
![image](https://github.com/Scofa26/AQA_MTS/assets/125700209/c77c9999-61ff-44f9-afba-b6b88907fb2a)

2023-11-28 15:25 UTC, Scofa26 commented on AQA_MTS/Program.cs
> +             if (Convert.ToDouble(sum3 / 2.0) == Convert.ToDouble(sum4 / 2.0)) Console.WriteLine("Средние арифметические равны ");
Да, тут ошиблась , исправила )

2023-12-11 14:09 UTC, wildpioneer commented
Проверено

2023-12-11 14:09 UTC, closed without merging