done Strings hw
Scofa26/AQA_MTS pull request #3
Opened 2023-11-26 20:26 UTC by Scofa26

2023-11-27 19:34 UTC, wildpioneer requested changes

2023-11-27 19:34 UTC, wildpioneer commented on Strings/Program.cs
> +            string newPath = "C:\\Users\\Scofa\\source\\repos\\AQA_MTS\\Strings\\input.txt";
Используем символ @ перед строкой чтобы не плодить двойные слеши

2023-11-27 19:34 UTC, wildpioneer commented on Strings/Program.cs
> +                Console.WriteLine(concat);
Форматирование

2023-11-28 05:22 UTC, Scofa26 commented on Strings/Program.cs
> +            string newPath = "C:\\Users\\Scofa\\source\\repos\\AQA_MTS\\Strings\\input.txt";
Console.WriteLine($"Задание1");

 string newPath = @"C:\Users\Scofa\source\repos\AQA_MTS\Strings\input.txt";
 string text = File.ReadAllText(newPath);

2023-11-28 05:23 UTC, Scofa26 commented on Strings/Program.cs
> +                Console.WriteLine(concat);
![image](https://github.com/Scofa26/AQA_MTS/assets/125700209/c9b54dce-d58b-4e2c-ab98-0799761979e9)

2023-11-28 05:23 UTC, Scofa26 commented
поправила

2023-12-11 14:08 UTC, wildpioneer commented
Проверено

2023-12-11 14:08 UTC, closed without merging